# Generated by Django 5.2.9 on 2026-01-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Mission', max_length=50)),
                ('description', models.TextField(default='We aim to address urbanisation challenges through eco-conscious design and innovation, setting benchmarks in sustainability, transparency, and global quality standards, while delivering projects that embody trust, excellence, and long-term value for our customers and society.')),
                ('css_class', models.CharField(help_text='Example: vision-section, mission-section, philosophy-section', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10)),
                ('title', models.CharField(default='Free Consultation', max_length=100)),
                ('description', models.TextField(default='Get expert property advice at no cost. Our team provides personalized guidance for your unique needs.')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('office_hours', models.CharField(default='Office Hours: Monday - Saturday, 9:00 AM - 7:00 PM', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IntroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Ready to Make a Move?', max_length=200)),
                ('description', models.TextField(default="Whether you're looking to buy flat or home our experienced team is here to guide you every step of the way. Share your requirements with us, and we'll help you find the perfect property match tailored to your needs and budget.")),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(default='Submit Your Requirements', max_length=100)),
                ('description', models.TextField(default="Tell us what you're looking for - budget, location, property type, and preferences.")),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Suresh Surya', max_length=100)),
                ('role', models.CharField(default=' Finance and Accounting Manager', max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('bio', models.TextField(default='Suresh Surya is a Chartered Accountant with over 7 years of professional experience in finance and accounting. Currently at Living Structures, he has spent the last 6 years managing financial operations within the real estate sector.')),
            ],
        ),
        migrations.CreateModel(
            name='top_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Find Your Dream Property Today!', max_length=200)),
                ('subtitle', models.TextField(default='Your journey to the perfect home starts here. Let our experts guide you every step of the way.', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='WHO WE ARE', max_length=50)),
                ('heading', models.CharField(default='A Bengaluru Developer Creating Sustainable,Future-Ready Living Spaces.', max_length=200)),
                ('top_image', models.ImageField(upload_to='about/')),
                ('bottom_image', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
