# Generated by Django 5.2.9 on 2026-01-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_label', models.CharField(default='Discover Your Dream Home', max_length=200)),
                ('content', models.TextField(default='Some representative placeholder content for the first slide.', max_length=200)),
                ('Carousel_image', models.ImageField(upload_to='carousel_images/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='QC-FIRST', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_titel', models.CharField(default='Welcome to our Website', max_length=100)),
                ('back_image', models.ImageField(upload_to='back image/')),
                ('para1', models.TextField(default='Your perfect home is no longer a dream.', max_length=50)),
                ('para2', models.TextField(default='Spacious 2 & 3 BHK homes on Sarjapur-Attibele Road.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(default='To constantly endeavour to be the Preferred Developer of Residential, Commercial and Hospitality spaces in the markets in which we operate, without compromising on our Core Values, for the benefit of all our Stakeholders.', max_length=500)),
                ('vision', models.TextField(default='To be a World-class Organisation in our Products, Processes, People and Performance.', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartments', models.CharField(default='132', max_length=50)),
                ('bhk_types', models.CharField(default='2 / 2.5 / 3', max_length=50)),
                ('towers', models.CharField(default='Beautifully Designed 7 Towers', max_length=50)),
                ('description', models.TextField(default='Nestled at the heart of the city, Living Structures offers a blissful living experience amidst greenery where serene natural vistas soothe the soul. Envisioned with modern urban living, this iconic residence is the epitome of dream living. Come and live your life at its best in the most coveted address where enchanting greens redefine your senses.')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
    ]
