# Generated by Django 5.2.9 on 2026-01-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmodel',
            old_name='main_titel',
            new_name='main_title',
        ),
        migrations.AddField(
            model_name='stat',
            name='subtitle',
            field=models.CharField(default='Years Experience', max_length=100),
        ),
        migrations.AddField(
            model_name='stat',
            name='title',
            field=models.CharField(default='Years Experience', max_length=100),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='Carousel_image',
            field=models.ImageField(upload_to='Carousel_images/'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='title',
            field=models.CharField(default='write points here', max_length=100),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='para1',
            field=models.TextField(default='Your perfect home is no longer a dream.', max_length=100),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='para2',
            field=models.TextField(default='Spacious 2 & 3 BHK homes on Sarjapur-Attibele Road.', max_length=100),
        ),
        migrations.AlterField(
            model_name='overview',
            name='apartments',
            field=models.CharField(default='132', max_length=100),
        ),
        migrations.AlterField(
            model_name='overview',
            name='bhk_types',
            field=models.CharField(default='2 / 2.5 / 3', max_length=100),
        ),
        migrations.AlterField(
            model_name='overview',
            name='towers',
            field=models.CharField(default='Beautifully Designed 7 Towers', max_length=100),
        ),
        migrations.AlterField(
            model_name='stat',
            name='icon',
            field=models.CharField(default='⌛', max_length=10),
        ),
        migrations.AlterField(
            model_name='stat',
            name='value',
            field=models.CharField(default='10+', max_length=100),
        ),
    ]
