# Generated by Django 5.2.9 on 2026-01-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(default='Your trusted real-estate partner helping you find your dream home.', max_length=200)),
                ('Footer_email', models.EmailField(default='Livingstructuresakura@gmail.com', max_length=254)),
                ('Footer_phone', models.CharField(default='+91 6364863933', max_length=20)),
                ('Footer_location', models.CharField(default='Bengaluru, India', max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('team_members', models.TextField(default='Mohan Reddy G, Nagesh K V, Suresh Surya, Bridged Suren', help_text='Enter member names separated by commas', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Content',
                'ordering': ['-created_at'],
            },
        ),
    ]
