# Generated by Django 5.2.9 on 2025-12-27 07:24

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=250)),
                ('main_card_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='card image/')),
                ('units', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('bhk_type_1', models.CharField(default='2 BHK', max_length=50)),
                ('bhk_units_1', models.PositiveIntegerField(default=44)),
                ('bhk_size_1', models.CharField(default='1445 Sq. ft', max_length=100)),
                ('bhk_price_1', models.CharField(default='Contact for Price', max_length=100)),
                ('bhk_type_2', models.CharField(default='3 BHK', max_length=50)),
                ('bhk_units_2', models.PositiveIntegerField(default=88)),
                ('bhk_size_2', models.CharField(default='1760 – 1890 Sq. ft', max_length=100)),
                ('bhk_price_2', models.CharField(default='Contact for Price', max_length=100)),
                ('land_parcel', models.CharField(default='2.1 Acres Land Parcel', max_length=100)),
                ('location', models.TextField(default='Sarjapur-Attibele Road')),
                ('welcome_title', models.CharField(default='Welcome to Our Project', max_length=200)),
                ('welcome_subtitle', models.TextField(default='Building the future, one idea at a time.')),
                ('landing_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('description_para1', models.TextField()),
                ('description_para2', models.TextField(blank=True, null=True)),
                ('highlights', models.TextField(help_text='Enter each highlight on a new line')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_title', models.CharField(default='Discover Our Story', max_length=200)),
                ('video_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Emoji or icon class', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='cards.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cards.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PropertySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('details', models.TextField(help_text='Enter each detail on a new line')),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='cards.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
